[package]
name = "taal_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.24", default-features = false, features = ["default_fonts"] }
once_cell = "1"
egui_extras = { version = "0.24", default-features = false, features = ["svg"] }
